########################################################
### eureka
########################################################
eureka.client.serviceUrl.defaultZone=@eureka.url.preProduct@

########################################################
### rabbitmq
########################################################
spring.rabbitmq.addresses=@mq.addresses.preProduct@
spring.rabbitmq.username=@mq.username.preProduct@
spring.rabbitmq.password=@mq.password.preProduct@

# 前缀，隔离不同环境的消息
tofocus.prefix=product

########################################################
### redis
########################################################
spring.redis.host=@redis.host.preProduct@
spring.redis.port=@redis.port.preProduct@
spring.redis.password=@redis.password.preProduct@
spring.redis.prefix=product

########################################################
### oauth2
########################################################
security.oauth2.client.access-token-uri=@tofocus.authentication.url.preProduct@/oauth/token
security.oauth2.client.user-authorization-uri=@tofocus.authentication.url.preProduct@/oauth/authorize
security.oauth2.resource.user-info-uri=@tofocus.authentication.url.preProduct@/userinfo

########################################################
### 数据库
########################################################
spring.datasource.url=@mysql.url.preProduct@/tf_product_account?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=tf_account
spring.datasource.password=ENC(7ubjoWHwNtbVsnCg9ID8EzCQz4rczUMh4rNf58w7H7tuGFgXEwioDFgMI9jYIB+T)

########################################################
### 文件服务
########################################################
tofocus.file.baseUrl=@tofocus.file.baseUrl.preProduct@