########################################################
### eureka
########################################################
eureka.client.serviceUrl.defaultZone=http://@eureka.hostname.test@:@eureka.port@/eureka/

########################################################
### rabbitmq
########################################################
spring.rabbitmq.addresses=@mq.addresses.test@
spring.rabbitmq.username=@mq.username.test@
spring.rabbitmq.password=@mq.password.test@

# 前缀，隔离不同环境的消息
tofocus.prefix=test

########################################################
### redis
########################################################
spring.redis.host=@redis.host.test@
spring.redis.port=@redis.port.test@
spring.redis.password=@redis.password.test@
spring.redis.prefix=test

########################################################
### oauth2
########################################################
security.oauth2.client.access-token-uri=http://@tofocus.authentication.host.test@:@tofocus.authentication.port@/oauth/token
security.oauth2.client.user-authorization-uri=http://@tofocus.authentication.host.test@:@tofocus.authentication.port@/oauth/authorize
security.oauth2.resource.user-info-uri: http://@tofocus.authentication.host.test@:@tofocus.authentication.port@/userinfo

########################################################
### 数据库
########################################################
spring.datasource.url=@mysql.url.test@/tofocus_account?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=@mysql.username.test@
spring.datasource.password=@mysql.password.test@

########################################################
### zipkin
########################################################
spring.zipkin.base-url=@zipkin.url.test@

########################################################
### 文件服务
########################################################
tofocus.file.baseUrl=@tofocus.file.baseUrl.test@