########################################################
### eureka
########################################################
eureka.client.serviceUrl.defaultZone=http://@eureka.hostname.release@:@eureka.port@/eureka/

########################################################
### rabbitmq
########################################################
spring.rabbitmq.addresses=@mq.addresses.release@
spring.rabbitmq.username=@mq.username.release@
spring.rabbitmq.password=@mq.password.release@

# 前缀，隔离不同环境的消息
tofocus.prefix=product

########################################################
### redis
########################################################
spring.redis.host=@redis.host.release@
spring.redis.port=@redis.port.release@
spring.redis.password=@redis.password.release@
spring.redis.prefix=product

########################################################
### oauth2
########################################################
security.oauth2.client.access-token-uri=@tofocus.authentication.url.release@/oauth/token
security.oauth2.client.user-authorization-uri=@tofocus.authentication.url.release@/oauth/authorize
security.oauth2.resource.user-info-uri: @tofocus.authentication.url.release@/userinfo

########################################################
### 数据库
########################################################
spring.datasource.url=@mysql.url.release@/tf_product_account?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=tf_account
spring.datasource.password=ENC(7ubjoWHwNtbVsnCg9ID8EzCQz4rczUMh4rNf58w7H7tuGFgXEwioDFgMI9jYIB+T)

########################################################
### zipkin
########################################################
spring.zipkin.base-url=@zipkin.url.release@

########################################################
### 文件服务
########################################################
tofocus.file.baseUrl=@tofocus.file.baseUrl.release@
