eureka.client.serviceUrl.defaultZone=http://eureka:20000/eureka/
spring.rabbitmq.addresses=rabbitmq:5672
spring.rabbitmq.virtual-host=/lejia-dev
spring.redis.prefix=dev
tofocus.prefix=dev
spring.elasticsearch.uris=http://elasticsearch:9200
spring.zipkin.enabled=false

security.oauth2.client.access-token-uri=http://lejia-account:21001/oauth/token
security.oauth2.client.user-authorization-uri=http://lejia-account:21001/oauth/authorize
security.oauth2.resource.user-info-uri=http://lejia-account:21001/userinfo

tofocus.file.baseUrl=http://lejia-file:21003/
tofocus.file.baseIntranetUrl=http://lejia-file:21003/
tofocus.file.root=/data/uploads
tofocus.file.backup=/data/backup
tofocus.file.backup.active=false

spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=filesystem:/app/migrations
