########################################################
### 应用配置
########################################################
tofocus.app.name=accountUtil
tofocus.app.version=@project.version@

server.servlet.register-default-servlet=true

jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}

spring.cloud.loadbalancer.retry.retryable-status-codes=503
spring.cloud.loadbalancer.retry.retry-on-all-operations=true

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

eureka.instance.prefer-ip-address=true

spring.main.allow-circular-references=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
########################################################
### redis
########################################################
spring.redis.lettuce.pool.max-active=-1
spring.data.redis.repositories.enabled=false

########################################################
### rabbitmq
########################################################
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.virtual-host=/

########################################################
### oauth2
### client-id 和 密码 请向云中心管理员申请
########################################################
security.oauth2.client.client-id=accountUtil
security.oauth2.client.client-secret=${ACCOUNT_UTIL_OAUTH_CLIENT_SECRET:CHANGE_ME}

########################################################
### 数据库
########################################################
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# HikariCP settings
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=5
# Java Persistence Api
spring.jpa.database = MYSQL
spring.jpa.show-sql = false
spring.jpa.hibernate.ddl-auto = validate
spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.open-in-view=true

spring.flyway.enabled=false

########################################################
### 监控
########################################################
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details= ALWAYS
management.metrics.tags.application:${spring.application.name}

########################################################
### 服务实例配置
### （每实例需要分别设置的配置项）
########################################################

