package cn.tofocus.lejia.exception;

import cn.tofocus.core.exception.ErrCode;

public enum LejiaErrCode implements ErrCode
{
    // @formatter:off
	NO_P0INTS("lejia-0101", "积分余额不足"),// 可现金直接购买
	NO_COMMS("lejia-0102", "余额不足"),
	WRONG_FARMER("lejia-0103","商品市场信息不匹配!"),
	ORDER_NULL("lejia-0104","订单明细不可为空!"),
	AMT_NULL("lejia-0105","订单金额不可为零!"),
	ORDER_DEL("lejia-0106","订单不存在!"),
	CARD_DEL("lejia-0107","卡券已失效!"),
	GOODS_NONUM("lejia-0108","库存不足!"),
	GOODS_DISABLED("lejia-0109","商品已下架!"),
	VENDOR_WRONG("lejia-0110","无效收款码!"),
	FARMER_OVERTIME("lejia-0111","该市场未营业!"),
	FARMER_OVERRANE("lejia-0112","超出配送范围!"),
	ORDER_OVERSTATUS("lejia-0113","订单状态异常!"),
	REFUND_NOPOINT("lejia-0114","市场订单不可退货!"),
	REFUND_NOSTATUS("lejia-0115","该订单状态不可申请退货!"),
	NOT_FIND_ORDER("lejia-0116","找不到订单!"),
	WRONG_TIME("lejia-0117","不要重复提交订单!"),
	WRONG_STATUS("lejia-0118","该订单已付款!"),
	WRONG_WEPAY("lejia-0119","调用微信支付失败!"),
	WRONG_GWCTYPE("lejia-0120","该商品不能加入购物车!"),
	WRONG_FORMID("lejia-0120","重复订单!"),
	WRONG_RE("lejia-0121","你已申请退款!"),
	BALANCE_INSUFFICIENT("lejia-0122","余额不足!"),
	COMMDRAW_UNTREATED("lejia-0123","还有提现未处理,请上一次提现处理后再申请!"),
	COMMDRAW_LEAST("lejia-0124","最小提现金额为10元!"),
	COMMDRAW_MAX("lejia-0125","最大提现金额为10000元!"),
	COMMDRAW_ONLY("lejia-0126","一天只能提现一次!"),
	DRAW_NUMBER("lejia-0127","今天的抽奖次数已经用完!"),
	ALREADYHERE_COLLAGEORDER("lejia-0128","您已经参加该团购!"),
	NOT_DRAW_RECORD("lejia-0129","没有中奖记录!"),
	GIFT_ERR("lejia-0130","礼品券异常!"),
	GWC_SPACE_NOTEXIST("lejia-0131","这个商品的规格已经下架！"),
	// 前端有用到判断这个code，请勿改变其对应含义
	GOODS_NUM_PURCHASENUM("lejia-0132","已经达到这个商品的限购"),
	SOME_DATA_INEXISTENCE("lejia-0133","删除时有部分数据已经不存在"),
	ASSIGNED_MORE_THRN_ONCE("lejia-0134","同一商品只能指派一个供应商一次"),
	SORT_REPEAT("lejia-0135","同一规格的商品派单顺序不能重复"),
	SORT_NOT_GREATER_THAN_ZERO("lejia-0136","同一商品的供应商采购派单顺序必须大于0"),
	PURCHASESTATUS_ERROR("lejia-0137","已确认完成或撤销的采购无法重新采购"),
	PURCHASESTATUS_ERROR2("lejia-0138","只有采购中或采购完成的采购订单可以确认完成"),
	PURCHASESTATUS_ERROR3("lejia-0139","该订单已经采购，无法操作"),
	NOT_FIND_ORDER_DETAIL("lejia-0140","找不到订单明细"),
	NOT_FIND_VENDOR_ORDER("lejia-0141","找不到商户订单信息"),
	DEEP_CLONE_FAILURE("lejia-0142","对象不支持深拷贝"),
	DATA_INEXISTENCE("lejia-0143","数据不存在"),
	APP_CONFIG_INEXISTENCE("lejia-0144","app配置不存在"),
	NOT_RIGHT("lejia-0145","没有权限"),
	PARAM_NOT_ALLOWED("lejia-0146","参数不允许传递"),
	MARKET_INEXISTENCE("lejia-0147","市场不存在"),
	DATA_NOT_EMPTY("lejia-0148","数据不能为空"),
	COURIER_NOT_REPEAT("lejia-0149","骑手不能重复"),
	PARAM_OVERSIZE("lejia-0150","参数长度超过限制"),
	EXCEED_THE_LIMIT("lejia-0151","超出限制"),
	DATA_NOT_ALLOWD("lejia-0152","数据不符合要求"),
	GET_BEAN_VALUE_FAILURE("lejia-0153","获取属性值失败"),
	MERCHANT_INEXISTENCE("lejia-0154","商户不存在"),
	COURIER_INEXISTENCE("lejia-0155","骑手不存在"),
	GOODS_MEMBERPRICE_ERR("lejia-0156","会员价不能大于现价"),
	CARD_INEXISTENCE("lejia-0157","优惠券不存在"),
	CARD_IS_EMPTY("lejia-0158","优惠券被领光了"),
	CARD_IS_RECEIVED("lejia-0158","优惠券已经被领取了"),
	GOODS_NAMEREPEAT("lejia-0159","商品名称不能重复填写"),
	GOODSSPACES_NAMEREPEAT("lejia-0160","商品规格名称不能重复填写"),
	PARAM_NULL_ERR("lejia-0161", "参数空异常"),
	GOODS_INEXISTENCE("lejia-0162","商品不存在!"),
	GOODS_IS_DELETED("lejia-0163","商品已删除!"),
	TIME_IS_ERROR("lejia-0164","时间格式不对！"),
    TIME_IS_OVER("lejia-0165","不在营业范围时间内"),
	CARD_ALREADY_RECEIVED("lejia-0166","当前卡券已领取"),
	REPORT_TIME_ERROR("lejia-0167","生成报表时间只能选当天之前一天"),
	VENDORT_INFO_NOT_NULL("lejia-0168","已经绑定银行卡用户,信息不能为空"),
	VENDORT_INFO_ERROR("lejia-0169","该商户不能修改身份信息和银行开户人名称"),
	TIME_ERROR("lejia-0170","开始日期不得大于结束日期"),
	UNABLE_TO_SETTLE("lejia-0171","请确认商户银行信息全部完善并正确后再次提交！"),
	SETTLE_ERROR("lejia-0172","该日期区间已产生结算记录"),
	MODEL_NULL("lejia-0173","该市场未设置结算模式"),
	SETTLEMENT_ERROR("lejia-0174","该结算异常,需联系银行人员勾销或清除解决"),
	VENDOR_REGISTERTIME_ERROR("lejia-0175","商户绑定银行清分系统时间是当天,不能当天清分 或者 商户还未绑定清分系统"),
	SETTLEMENT_AMT_ERROR("lejia-0176","结算的金额和入账的金额不相同!"),
	VENDOR_NOT_ZERO_ERROR("lejia-0177","不能选择自采"),
	PURCHASE_PRICE_ERROR("lejia-0178","采购价不能大于商品销售价"),
	SETTLEMENT_ORDER_ERROR("lejia-0179","有采购订单还未确认,不能结算"),
	CARD_INVALID("lejia-0180","卡券已经失效,无法使用"),
	CARD_REPEAT_ERROR("lejia-0181","用户已领取过该卡券,无法再次 发放(领取)!"),
	FARMER_TIME_ERROR("lejia-0182","营业时间设置有误!"),
	PASSWD_ERROR("lejia-0183","登录密码错误!"),
	GOODS_ERROR("lejia-0184","商品找不到"),
	GOODS_GTYPE_ERROR("lejia-0185","限制商品和限制品类有误!"),
	CARD_USER_ERROR("lejia-0186","该优惠券无法使用!"),
	VENDOR_ERROR("lejia-0187","商户不存在"),
	DELIVERY_PICKUP_ERROR("lejia-0188","配送和自提不能同时关闭"),
	GWC_DELIVERY_PICKUP_ERROR("lejia-0189","配送方式不统一无法一起结算"),
	KC_ZERO_ERROR("lejia-0190","库存最低为零"),
	MOBILE_ERROR("lejia-0191","手机号码重复"),
	GTYPE_NOT_GOODS("lejia-0192","当前无任何售卖商品"),
	GTYPE_NOT_COUPON("lejia-0193","当前无优惠券分类"),
	GTYPE_NOT_GOODSMAIN("lejia-0194","当前商品分类不属于优惠券分类下"),
	CARD_EFFECTIVE_ONE("lejia-0195","卡券有效期必须要有"),
	GOODS_FARMER_ERROR("lejia-0196","限制市场有误!"),
	USERFARMER_NOT_EMPTY("lejia-0197","限制市场不能为空"),
	USERVENDOR_NOT_EMPTY("lejia-0198","限制商户不能为空"),
	SETTLEMENT_DATE_ERROR("lejia-0199","存在未确定的订单无法结算"),
	PKEY_NOT_EMPTY("lejia-0200","主键不能为空"),
	PROMOTE_ERROR("lejia-0201","推广编辑失败"),
	ENABLED_ERROR("lejia-0202","推广启动中，无法修改或删除"),
	ENABLED_START_ERROR("lejia-0203","推广状态只能启动一个"),
	STARTINGPRICE_ERROR("lejia-0204","低于起送价,无法下单"),
	PRESALEGOODS_DELIVERY_TIME_ERROR("lejia-0205","发货时间不能为空"),
	PRESALEGOODS_TIME_ERROR("lejia-0206","发货时间不能早于上架时间"),
	SETTLEMENTMETHODTYPE_COMMISSION_ERROR("lejia-0207","佣金结算需要填写费率"),
	PROBLEMTYPE_NOTEXIST("lejia-0208","常见问题分类不存在"),
	PROBLEMTYPE_NOTUPDATED("lejia-0209","这个常见问题分类不能修改或删除"),
	PROBLEMTYPE_NAMEERROR("lejia-0210","不能使用这个名称"),
	XASZ_PAY_ERROR("lejia-0211", "支付失败"),
	DEFAULT_PROBLEMTYPE_ERROR("lejia-0212", "默认问题不能修改或删除"),
	SEC_WANLI_ERROR("lejia-0213", "当前市场无法使用第三方派送"),
	SEC_WANLI_RESULT_ERROR("lejia-0214", "第三方派送有异常"),
	VENDOR_SHOPPING_MALL_VENDOR_ERROR("lejia-0215", "商户必填"),
	VENDOR_SHOPPING_MALL_SUPPLY_ERROR("lejia-0216", "商户商城类型市场,不可修改商品供应库"),
	VENDOR_SHOPPING_MALL_VENDOR_INS_ERROR("lejia-0217", "商户商城类型市场,不能在新增商户"),
	ENABLED_TRUE_NOT_DEL("lejia-0218", "启用中,无法删除"),
	GTYPE_NOT_VENDOR("lejia-0219","当前无任何商户"),
	VENDORBOUTIQUE_ONE_ERROR("lejia-0220","精选商户只能设置一个"),
	GOODS_VENDOR_NAMEREPEAT("lejia-0221","同一个商户,商品名称不能重复填写"),
	MEMBER_NOT_LOGIN("lejia-0222","请先登陆!"),
	VENDORBOUTIQUE_ENABLED_TRUE_ERROR("lejia-0223","请先启用商户"),
	VENDOR_WALLET_AMOUNT_ERROR("lejia-0224","商户余额不足"),
	MEMBER_NOT_ERROR("lejia-0225","会员不存在"),
	REFUND_LINE_NUM_ERROR("lejia-0226","退款数量不能大于购买数量"),
	REFUND_LINE_AMT_ERROR("lejia-0227","退款金额大于能退货的金额"),
	REFUND_STATUS_ERROR("lejia-0228","退款订单已处理"),
	VENDOR_ORDER_REFUND_ERROR("lejia-0229","有退款申请,无法重新采购"),
	VENDOR_ORDER_SETTLEMENTTYPE_REFUND_ERROR("lejia-0230","已经结算,无法申请退款"),
	LINSHI_HUODONG_ERROR("lejia-0231","每位用户限购二份"),
	LINSHI_HUODONG_END_ERROR("lejia-0232","该活动已经结束"),
	LINSHI_HUODONG_COUPON_ERROR("lejia-0233","优惠券一天只能用一张"),
	LINSHI_HUODONG_COUPON_RECEIVE_ERROR("lejia-0234","该商户优惠券只能领取一次"),
	ORDER_DISTRIBUTIONTYPE_ERROR("lejia-0235","当前订单不允许切换配送方式"),
	DELIVERY_ADDR_ERROR("lejia-0236","配送地址异常"),
	LINSHI_HUODONG_CLICK_ERROR("lejia-0237","不要重复点击"),
	IMPORT_PHOTO_IS_ERROR("lejia-0238","图片格式不对"),
    LINSHI_HUODONG_START_ERROR("lejia-0239","该活动未开始"),
	GIFT_NOT_FOUND("lejia-0240","找不到礼品券"),
    LINSHI_CARD_DAYNUM_ISEMPTY("lejia-0241","今日优惠券被领光了"),
	GIFT_INVALID("lejia-0242","礼品券已失效"),
	ACTIVITY_NOT_FOUND("lejia-0243","找不到卡券活动"),
	ACTIVITY_HAS_NO_COUPON("lejia-0244","卡券活动没有卡券了"),
	ACTIVITY_DISABLED("lejia-0245","卡券活动未启用"),
	ACTIVITY_NOT_STARTED("lejia-0246","卡券活动未开始"),
	ACTIVITY_ENDED("lejia-0247","卡券活动已结束"),
	ACTIVITY_NO_STOCK("lejia-0248","卡券活动已经抢光了"),
	ACTIVITY_TODAY_NO_STOCK("lejia-0249","今日的卡券活动已经抢光了，请明天再来"),
	ACTIVITY_MEMBER_TIMES_LIMIT("lejia-0250","用户参与次数已到上限"),
	GIFT_IS_EMPTY("lejia-0251","礼品券被领光了"),
	EXPRESS_ERROR("lejia-0252","第三方派单不能后台手动确认"),
	NO_QRCODE_DINEIN_ERROR("lejia-0253","不是扫码进来,不能使用堂食"),
	GOODS_BOX_GWC_ONLY_ERROR("lejia-0254","已选择其他包厢"),
	DESKTOP_ERROR("lejia-0255","桌位号重复"),
	GOODS_BOX_ERROR("lejia-0256","一笔订单只能预订一个包厢"),
	COUPON_ERROR("lejia-0257","优惠券异常"),
	COUPON_ERROR1("lejia-0258","还未开始核销"),
	COUPON_ERROR2("lejia-0259","卡券已使用"),
	COUPON_ERROR3("lejia-0260","卡券已过期"),
	COUPON_ERROR4("lejia-0261","卡券已禁用"),
	WEIXIN_AGREE_ERROR("lejia-0262","无法向微信提起退款申请"),
	TAG_NOT_FOUND("lejia-0263","找不到标签"),
	TAG_NAME_EXIST("lejia-0264","标签名称已存在"),
	CLICK_FAST_ERROR("lejia-0265","点击太快了,请稍等"),
	PICKUP_TIME_ERROR("lejia-0266","自提时间不能为空"),
	H5_SPACE_ERROR("lejia-0267","该规格已售罄"),
	H5_BOX_LEVEL_ERROR("lejia-0268","该包厢目前不可预定"),
	SUPPLIER_NOT_FOUND("lejia-0269","找不到供应商"),
	SUPPLIER_ENABLED_CANNOT_DEL("lejia-0270","供应商为启用状态，不能删除"),
	SUPPLIER_NAME_EXIST("lejia-0271","供应商名称已存在"),
	REMOTE_REQUEST_ERROR("lejia-0272", "远程请求返回的错误"),
	SUPPLIER_NO_EXPRESS_CONFIG("lejia-0273","供应商未配置快递参数"),
	RECEIVE_INFO_NOT_FOUND("lejia-0274","找不到收件信息"),
	ORDER_EXPRESS_NOT_FOUND("lejia-0275","找不到物流单"),
	EXPRESS_CANCEL_ERROR("lejia-0276","物流取消失败"),
	LOGIN_MOBILE_NOT_FOUND("lejia-0277","手机号不支持登录"),
	LOGIN_MOBILE_DISABLED("lejia-0278","手机号用户已禁用"),
	SUPPLIER_ORDER_NO_VERIFY_PERMISSION("lejia-0279","不能核销其他商户的订单"),
	INTEGRALPRESALEGOODS_TIME_ERROR("lejia-0280","上架时间不能为空"),
	INTEGRALPRESALEGOODS_TIME_ERROR2("lejia-0281","下架时间不能为空"),
	ORDER_REFUND_STATUS_ERROR("lejia-0282", "当前有一笔退款订单还未处理"),
	MEMBER_MANAGER_ERROR("lejia-0283", "用户不存在,无法添加"),
	MANAGER_MOBILE_ERROR("lejia-0284", "手机号码重复,无法添加"),
	ZX_PAYCOMM_ERROR("lejia-0285", "中信清分,手续费有误,无法清分"),
	PARAM_VALUE_ERR("lejia-0286", "参数数值错误异常"),
	REQUEST_OUT_ERROR("lejia-0288", "请求外部系统失败"),
	ZX_USERID_ERROR("lejia-0289", "有清分的用户没用绑卡,请先绑卡后,再清分"),
	FARMER_CONFIG_NOT_FOUND("lejia-0290", "找不到市场配置"),
	COMMISSIONRATE_ERROR("lejia-0291", "佣金费率太低"),
	ZX_VENDOR_ERROR("lejia-0292", "商户未绑定银行卡,无法提现"),
	GOODS_RECOMMEND_MAX("lejia-0293", "推荐商品数量已达到上限"),
	NO_MSD("lejia-0294", "热力豆不足"),
	TEMPLATE_DOWNLOAD_ERROR("lejia-0295", "下载模板失败"),
	IMPORT_ERROR("lejia-0296", "导入失败"),
	EXPORT_ERROR("lejia-0297", "导出失败"),
	DELIVERY_PICKUP_ERRPOR("lejia-0298", "自提和配送不能都为空"),
	RECHARGECARD_NUMBER_ERROR("lejia-0299", "充值卡券不存在"),
	RECHARGECARD_DEADLINE_ERROR("lejia-0300", "充值卡券已超过可使用日期"),
	RECHARGECARD_CARDPASSWORD_ERROR("lejia-0301", "充值卡券卡密有误"),
	RECHARGECARD_ASCRIPTION_ERROR("lejia-0302", "该充值卡券不归属于当前小程序"),
	RECHARGECARD_UNUSED_CANCEL_ERROR("lejia-0303", "未使用的卡券才能作废"),
	RECHARGECARD_UNUSED_ERROR("lejia-0304", "卡券已作废"),
	ZX_PAY_REFUND_ERROR("lejia-0305", "中信退款失败"),
	ORDER_STATUS_REFUND_ERROR("lejia-0306", "待发货或已发货状态的订单才可以退款"),
	JD_GOODS_EXCEL_ERROE("lejia-0307","导入京东商品有误"),
	JD_REFUND_ERROR("lejia-0308","京东商品退货/换货有问题"),
	JD_GOODS_GWC_ERROR("lejia-0309","该商品当前所在地区无货，暂无法加入购物车"),
	JD_GOODS_LOWEST_BUY_ERROR("lejia-0310","该商品有最低起购量"),
	JD_GOODS_ADDR_LONGITUDE_LATITUDE_ERROR("lejia-0311","请开启定位权限/添加收货地址"),
	JD_CATEGORY_TWO_ERROR("lejia-0312","京东分类不存在或不是二级分类"),
	CATERING_ERROR("lejia-0312","组合支付不支持第三方餐饮系统"),
	MALL_CATEGORY_TWO_ERROR("lejia-0313","商城分类不存在或不是二级分类"),
	PAYTYPE_ERROR("lejia-0313","支付方式有误"),
	MSD_PAYTYPE_ERROR("lejia-0314","当前商品不支持热力豆支付"),
	MSD_ORDERSTATUS_WAIT_ERROR("lejia-0315","您选择了非民生订单或订单状态不符，请重新选择！"),
	;

    // @formatter:on
    
    private final String code;
    
    private final String description;
    
    private LejiaErrCode(String code, String description)
    {
        this.code = code;
        this.description = description;
    }
    
    @Override
    public String getCode()
    {
        return code;
    }
    
    @Override
    public String getDescription()
    {
        return description;
    }
    
    @Override
    public boolean equalsCode(String code)
    {
        return this.code.equals(code);
    }
}
