########################################################
### eureka
########################################################
eureka.client.serviceUrl.defaultZone=@eureka.url.productNp@

########################################################
### rabbitmq
########################################################
spring.rabbitmq.addresses=@mq.addresses.productNp@
spring.rabbitmq.username=@mq.username.productNp@
spring.rabbitmq.password=@mq.password.productNp@

# 前缀，隔离不同环境的消息
tofocus.prefix=product

########################################################
### redis
########################################################
spring.redis.host=@redis.host.productNp@
spring.redis.port=@redis.port.productNp@
spring.redis.password=@redis.password.productNp@
spring.redis.prefix=product

########################################################
### oauth2
########################################################
security.oauth2.client.access-token-uri=@tofocus.authentication.url.productNp@/oauth/token
security.oauth2.client.user-authorization-uri=@tofocus.authentication.url.productNp@/oauth/authorize
security.oauth2.resource.user-info-uri=@tofocus.authentication.url.productNp@/userinfo

########################################################
### 数据库
########################################################
spring.datasource.url=@mysql.url.productNp@/tf_product_file?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=tf_file
spring.datasource.password=ENC(hSAXbs+j2M8BP5oaraNI4DQpQ4DK4t/U/WroVG6g2H3QqHL4w9V2+TQgp/bBwd6t)

########################################################
### zipkin
########################################################
spring.zipkin.base-url=@zipkin.url.productNp@

########################################################
### ES
########################################################
spring.elasticsearch.uris=@es.rest.productNp@

########################################################
### 文件服务
########################################################
tofocus.file.baseUrl=@tofocus.file.baseUrl.productNp@
tofocus.file.baseIntranetUrl=@tofocus.file.baseIntranetUrl.productNp@