########################################################
### eureka
########################################################
eureka.instance.hostname=@eureka.hostname.singleton@

eureka.client.serviceUrl.defaultZone=http://@eureka.hostname.singleton@:@eureka.port@/eureka/
