########################################################
### eureka
########################################################
eureka.instance.hostname=@eureka.hostname.release@

eureka.client.serviceUrl.defaultZone=http://@eureka.hostname.release@:@eureka.port@/eureka/
