########################################################
### eureka
########################################################
eureka.instance.hostname=@eureka.hostname.singletonHW@

eureka.client.serviceUrl.defaultZone=http://@eureka.hostname.singletonHW@:@eureka.port@/eureka/
