########################################################
###
###   Active Profiles
###   
### 配置文件加载顺序，common，环境配置，running。后面的配置会重载前面的配置
### 
### 环境配置可选以下4项：
###
### local = 本地开发环境
### test = 91 测试环境用于开发测试
### release = 94 测试环境用于测试release版
### preProduct = 预生产环境
### productHW = 华为 生产环境
### singletonHW = 华为singleton 生产环境
### 
########################################################
spring.profiles.active=common,local,running

########################################################
### 应用配置
### 配置应用名和端口号
########################################################
spring.application.name=eureka-server
server.port=@eureka.port@
