########################################################
### eureka
########################################################
eureka.server.enable-self-preservation=false

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

########################################################
### 日志级别配置
########################################################
logging.level.root=INFO

spring.main.allow-circular-references=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher


########################################################
### 监控
########################################################
management.endpoints.web.exposure.include=info
management.metrics.tags.application:${spring.application.name}