########################################################
### eureka
########################################################
eureka.instance.hostname=server0

eureka.client.serviceUrl.defaultZone=@eureka.url.productHW@
