########################################################
### eureka
########################################################
eureka.instance.hostname=@eureka.hostname.test@

eureka.client.serviceUrl.defaultZone=http://@eureka.hostname.test@:@eureka.port@/eureka/
