#!/bin/bash
set -euo pipefail

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${BUSINESS_DB_NAME}\` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${ACCOUNT_DB_NAME}\` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${FILE_DB_NAME}\` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${BUSINESS_DB_USER}'@'%' IDENTIFIED BY '${BUSINESS_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${ACCOUNT_DB_USER}'@'%' IDENTIFIED BY '${ACCOUNT_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${FILE_DB_USER}'@'%' IDENTIFIED BY '${FILE_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON \`${BUSINESS_DB_NAME}\`.* TO '${BUSINESS_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${ACCOUNT_DB_NAME}\`.* TO '${ACCOUNT_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${FILE_DB_NAME}\`.* TO '${FILE_DB_USER}'@'%';
FLUSH PRIVILEGES;
SQL

