# 前缀，隔离不同环境的消息
tofocus.prefix=product

########################################################
### 数据库
########################################################
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=root
spring.datasource.password=${FILE_EXAMPLE_DB_PASSWORD:CHANGE_ME}

########################################################
### 文件服务
########################################################
tofocus.file.baseUrl=@tofocus.file.baseUrl.release@
tofocus.file.baseIntranetUrl=@tofocus.file.baseIntranetUrl.release@
