########################################################
### 应用配置
########################################################
tofocus.app.name=\u6587\u4EF6\u670D\u52A1
tofocus.app.version=@project.version@

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

spring.main.allow-circular-references=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

########################################################
### 数据库
########################################################
spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.schema-locations=classpath:db/table.sql
spring.sql.init.platform=h2
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=5
# Java Persistence Api
spring.jpa.show-sql = false
spring.jpa.hibernate.ddl-auto = validate

########################################################
### 服务实例配置
### （每实例需要分别设置的配置项）
########################################################
tofocus.file.baseUrl=http://localhost:21003/
tofocus.file.root=uploads
tofocus.file.backup=filebackup
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
tofocus.file.oldApiLimit=-1

tofocus.exception.skipstatck:00300009,00300012
