########################################################
### eureka
########################################################
eureka.client.serviceUrl.defaultZone=http://@eureka.hostname.singleton@:@eureka.port@/eureka/

########################################################
### rabbitmq
########################################################
spring.rabbitmq.addresses=@mq.addresses.singleton@
spring.rabbitmq.username=@mq.username.singleton@
spring.rabbitmq.password=@mq.password.singleton@

# 前缀，隔离不同环境的消息
tofocus.prefix=singleton

########################################################
### redis
########################################################
spring.redis.host=@redis.host.singleton@
spring.redis.port=@redis.port.singleton@
spring.redis.password=@redis.password.singleton@
spring.redis.prefix=@tofocus.prefix@

########################################################
### oauth2
########################################################
security.oauth2.client.access-token-uri=http://@tofocus.authentication.host.singleton@:@tofocus.authentication.port@/oauth/token
security.oauth2.client.user-authorization-uri=http://@tofocus.authentication.host.singleton@:@tofocus.authentication.port@/oauth/authorize
security.oauth2.resource.user-info-uri: http://@tofocus.authentication.host.singleton@:@tofocus.authentication.port@/userinfo

########################################################
### 数据库
########################################################
tofocus.file.baseUrl=@tofocus.file.baseUrl.singleton@
wei.xin.config.app.id=@wei.xin.config.app.id.ymkt@
wei.xin.config.mch.id=@wei.xin.config.mch.id.ymkt@
wei.xin.config.re.url=@wei.xin.config.re.url.ymkt@
wei.xin.pay.abbreviations.name=致一云农贸
wei.xin.pay.full.name=浙江致一云农贸科技有限公司

spring.datasource.url=@mysql.url.singleton@/zyysc?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=@mysql.username.singleton@
spring.datasource.password=@mysql.password.singleton@
#spring.datasource.username=lejia

########################################################
### 中信对接
########################################################
zx.pay.notify.url=@zx.pay.notify.url.singleton@
