########################################################
### eureka
########################################################
eureka.client.serviceUrl.defaultZone=http://@eureka.hostname.product@:@eureka.port@/eureka/

########################################################
### rabbitmq
########################################################
spring.rabbitmq.addresses=@mq.addresses.product@
spring.rabbitmq.username=@mq.username.product@
spring.rabbitmq.password=@mq.password.product@

# 前缀，隔离不同环境的消息
tofocus.prefix=product

########################################################
### redis
########################################################
spring.redis.host=@redis.host.product@
spring.redis.port=@redis.port.product@
spring.redis.password=@redis.password.product@
spring.redis.prefix=@tofocus.prefix@

########################################################
### oauth2
########################################################
security.oauth2.client.access-token-uri=http://@tofocus.authentication.host.product@:@tofocus.authentication.port@/oauth/token
security.oauth2.client.user-authorization-uri=http://@tofocus.authentication.host.product@:@tofocus.authentication.port@/oauth/authorize
security.oauth2.resource.user-info-uri: http://@tofocus.authentication.host.product@:@tofocus.authentication.port@/userinfo

########################################################
### 数据库
########################################################
tofocus.file.baseUrl=@tofocus.file.baseUrl.product@
wei.xin.config.app.id=@wei.xin.config.app.id.lejia@
wei.xin.config.mch.id=@wei.xin.config.mch.id.lejia@
wei.xin.config.re.url=@wei.xin.config.re.url.lejia@
wei.xin.pay.abbreviations.name=致一云农贸
wei.xin.pay.full.name=浙江致一云农贸科技有限公司


spring.datasource.url=@mysql.url.product@/zyysc?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=@mysql.username.product@
spring.datasource.password=@mysql.password.product@

