<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>tfcloud-account-api</artifactId>
	<packaging>jar</packaging>

	<name>tfcloud-account-api</name>
	<description>tfcloud account api</description>
	<version>2.7.2</version>

	<parent>
		<groupId>cn.tofocus</groupId>
		<artifactId>tfcloud-account</artifactId>
	    <version>3.5.4</version>
	</parent>

	<properties>
	</properties>

	<build>
	</build>

	<dependencies>
	    <!-- 本地项目依赖 -->
		<dependency>
			<groupId>cn.tofocus</groupId>
			<artifactId>tfcloud-core</artifactId>
		</dependency>
	    <!-- 本地项目依赖 结束-->

	</dependencies>

</project>